### PR TITLE
add additional arguements from original pfetch

### PR DESCRIPTION
**Pull request by OldWorldOrdr**

### CODE REVIEW

**Comment by Gobidev** [comment]
Thank you for contributing^^

I hope you understand but I think that if pfetch should support flags, it should be proper support (i.e. using `clap`) with a help menu and possibly a man-page. I also don't think that printing the version number should be necessary because the only reason to update the program should be if something with the current setup is not working properly, otherwise the version doesn't really matter.

This project is supposed to be a rewrite of the original pfetch with pretty much the same features and therefore should (like pfetch) stay minimalistic (because that is what differentiates it from other fetch utilities like neofetch).

I should probably add some information somewhere on what I have in mind for this project  so that no time is wasted implementing features that I don't think fit pfetch.

**Comment by OldWorldOrdr** [comment]
the original pfetch printed its version with -v, adding --version was to be complete, even if its not that important it still technically brings it closer to the original

**Comment by Gobidev** [comment]
Sorry, I didn't know that😅 I will look into whether it is worth it to parse the arguments with clap or not. If not this is a good solution.

**Comment by OldWorldOrdr** [comment]
If we want to implement everything then here is the code that parses arguments from the original.
Besides version there is the help menu and a debug mode.
Screenshot from 2023-04-05 17-22-12

**Comment by OldWorldOrdr** [comment]
I added a help menu.  I don't know how to get the executable name automaticly in rust like the original does so I just hardcoded pfetch as the executable name.

**Review by Gobidev — APPROVED** [review]

**Comment by Gobidev** [comment]
Thank you!

**Pull request merged**
